version: "3.9"

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: resources
      MARIADB_USER: hms_user
      MARIADB_PASSWORD: hms_password
      TZ: Asia/Bangkok
    command: --bind-address=0.0.0.0 --default-time-zone=+07:00
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3030:3030"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - DB_HOST=mariadb
      - DB_USER=hms_user
      - DB_PASSWORD=hms_password
      - DB_NAME=resources
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:

